name: release
on:
  create:
    tags:
      - v*
  push:
    branches:
      - main

# Note the only differences between release and canary-release jobs are:
# - only canary passes --overwrite flag
# - the VERSION make variable passed to 'make dist checksum' is expected to
#   be "canary" if the job is triggered by a push to "main" branch. If the
#   job is triggered by a tag push, VERSION should be the tag ref.
jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # pin@v3.2.0

      - name: Setup Go
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # pin@3.5.0
        with:
          go-version: '1.20'
      
      - name: Run unit tests
        run: make test-coverage

      - name: Build Helm Binaries
        run: |
          make build-cross
          make dist checksum VERSION="${{ github.ref_name }}"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: _dist/helm-*

  canary-release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout source code
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # pin@v3.2.0

      - name: Setup Go
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # pin@3.5.0
        with:
          go-version: '1.20'

      - name: Run unit tests
        run: make test-coverage

      - name: Build Helm Binaries
        run: |
          make build-cross
          make dist checksum VERSION="canary"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: _dist/helm-*
